# 生成 assets_gen.go：把 config.example.json 与 web/index.html 以 base64 打进二进制。
# 用法: powershell -ExecutionPolicy Bypass -File scripts/gen_assets.ps1
param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)
$ErrorActionPreference = "Stop"

$ex = [System.IO.File]::ReadAllBytes((Join-Path $Root "config.example.json"))
$html = [System.IO.File]::ReadAllBytes((Join-Path $Root "web/index.html"))
$b64ex = [Convert]::ToBase64String($ex)
$b64html = [Convert]::ToBase64String($html)

$nl = [char]10
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Code generated by scripts/gen_assets.ps1; DO NOT EDIT.")
[void]$sb.AppendLine("package main")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("import `"encoding/base64`"")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("func mustDecodeBase64(s string) []byte {")
[void]$sb.AppendLine("`tb, err := base64.StdEncoding.DecodeString(s)")
[void]$sb.AppendLine("`tif err != nil {")
[void]$sb.AppendLine("`t`tpanic(`"assets decode: `" + err.Error())")
[void]$sb.AppendLine("`t}")
[void]$sb.AppendLine("`treturn b")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("var exampleConfig = mustDecodeBase64(`"$b64ex`")")
[void]$sb.AppendLine("var indexHTML = mustDecodeBase64(`"$b64html`")")

[System.IO.File]::WriteAllText((Join-Path $Root "assets_gen.go"), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output ("assets_gen.go written: " + (Get-Item (Join-Path $Root "assets_gen.go")).Length + " bytes")

